source "https://rubygems.org"

# use local theme gem for testing
group :jekyll_plugins do
  # gem "jekyll-archives"
  gem "jekyll-paginate"
  gem "jekyll-sitemap"
  gem "jekyll-gist"
  gem "jekyll-feed"
  gem "jemoji"
end

gem "wdm", "~> 0.1.0" if Gem.win_platform?
